apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jdiv4l7ny-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jdiv4l7ny-nodejs 
  name: jdiv4l7ny-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: jdiv4l7ny-nodejs 
